### ISSUE TITLE
Code HTML pour les lecteurs d'écrans

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/epikoinos#2]
@hiwelo À l'oral, le HCEhf préconise ça :

> Utiliser les mots et/ou adjectifs au féminin et au masculin, par ordre alphabétique dans la mesure du possible.

Exemple : lycéen.ne.s => lycéennes et lycéens

**Comment by hiwelo** [comment]
Sympa, je vais tâcher de mettre ça comme fallback oral pour les lecteurs d'écrans

**Comment by hiwelo** [comment]
Si tu veux que je t'ajoute un moyen dans le HTML de lire correctement le contenu du champ, il faudrait une méthode dans la classe Converter par exemple qui me retourne exactement le féminin et le masculin du mot demandé.
C'est possible d'adapter ton code en conséquence ?

**Comment by Rudloff** [comment]
J'ai modifié la fonction `Converter::convertWord()` pour qu'elle retourne des tableaux associatifs au lieu de chaînes (d3e13885185a325360aea2af9b9ad1166c423337). Tu devrais avoir ce qu'il te faut dedans.

**Comment by hiwelo** [comment]
J'ai pas vraiment ce qu'il me faut 😅
Pour `utilisateur`, cette fonction me retourne:
```php
array(1) { [0]=> string(16) "utilisateur.rice" }
```

Il me faudrait un tableau qui me retourne quelque chose du genre :
```php
array(1) { 
    [0] => array(3) { 
        ['epicene'] => string(16) "utilisateur.rice", 
        ['feminin'] => string(12) "utilisatrice", 
        ['masculin'] => string(11) "utilisateur" 
    } 
}
```

**Comment by Rudloff** [comment]
Tu es bien sur la branche develop ?

**Comment by hiwelo** [comment]
aaaaaaah 😁 peut-être pas 😅
Je teste ça ce soir.

**Comment by Rudloff** [comment]
Close by #14.
